### ISSUE TITLE
Perform type checks on all input.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#142]
Check the data types for all variables passed to every public method in the engine.

**Comment by seisatsu** [comment]
Halfway there with 2fef9184ed814ca970f728a7c6fc9cdd8e088063.

**Comment by seisatsu** [comment]
As of 3c24f3a I added some checks so you can see how to use them.

**Comment by pmer** [comment]
Oh, I just thought of another way to approach this problem: we could provide support for static type checking. Since static analysis happens before runtime, it won't slow Driftwood down during runtime.

Here's how it would work:

-  Add the now-official-in-3.5 type hints to our function definitions https://docs.python.org/3/whatsnew/3.5.html#pep-484-type-hints
- Try it out ourselves with [mypy](http://mypy-lang.org) or PyCharm. We should start seeing type errors.
  - We'll probably have to change how game scripts access the Driftwood variable since PyCharm reports it as an error right now.
- Document how to type check your game in the user docs & encourage game authors to do so.

If this sounds interesting I could try poking around with it in a new branch.

**Comment by pmer** [comment]
Python 3.6 adds syntax to annotate the types of variables, too https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations but we will only have access to that once the minimum Python version is bumped to 3.6.

**Comment by pmer** [comment]
Static type checking will not prevent the engine from crashing.

Instead, it will show game authors the type errors they are making while they're developing their game, and will allow them to have higher confidence things will work when they go to distribute their game.

**Comment by seisatsu** [comment]
That looks interesting. Can you put a demonstration together?

**Comment by pmer** [comment]
I'll try.

**Comment by pmer** [comment]
Static type checking is a separate mechanism from runtime type checking, so progress on this issue can continue unabated in the meantime.

**Comment by seisatsu** [comment]
We need to make sure whatever we do isn't causing a ton of lag.

**Comment by pmer** [comment]
Can you figure that out? And should we continue marking 0.0.8 as blocking on this issue?

**Comment by pmer** [comment]
Maybe try making different numbers of calls per frame & measuring the impact it has on performance on different hardware you own.

**Comment by pmer** [comment]
Oops just realized this isn't on 0.0.8!

**Comment by pmer** [comment]
On an Intel i5-5257U, each call to `TickManager.register()` now takes an additional 0.0001% CPU.

If you make 20,000 register/unregister calls per frame and, magically, the rest of the engine took no cycles, the CPU would be pegged at ~100%.

I don't have a good idea of how many engine API calls a game will make, but I expect that the only time when you'd have a lot would be during area loads and those don't happen too frequently.

@seisatsu Can you test on lower end hardware? That's probably the more relevant case anyway.

**Comment by seisatsu** [comment]
Yeah I'll test on an rpi 1.

**Comment by seisatsu** [comment]
Pretty much done here as of 41024929ad675400a9ae6f85e45311cd81917e80. Performance issues across all subsystems can be tested by profiling a run of the engine.

**Comment by pmer** [comment]
Nice work!
