### ISSUE TITLE
Draw only visible tiles on first frame.

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Driftwood#165]
Fix the first frame issue from Pull Request #161.

**Comment by pmer** [comment]
This issue blocks #157.

**Comment by pmer** [comment]
I think this issue also causes the following flicker.

![black flash](https://user-images.githubusercontent.com/107998/31069076-a24b863c-a70f-11e7-90b4-64d5c5dfe78f.gif)

**Comment by pmer** [comment]
I think `FrameManager.frame()` is designed so that the world author can perform custom frame draws. But it occurs to me that currently, `Area.tick()` draws the area every frame, which would seemingly defeat any such attempt by world authors.

https://github.com/seisatsu/Driftwood/blob/a5092dcf6dcc140d630fe4e55bd7e9e7363280ce/src/framemanager.py#L141

@seisatsu Do you want to keep this feature? If so, let's come up with a way to make it happen well. Otherwise, being able to remove the feature will make fixing this bug a bit simpler.

**Comment by seisatsu** [comment]
Remove it for now, I see no reason we can't do the same thing with overlays.
