### ISSUE TITLE
Edges of area not cleared when area rumbling

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#75]
# Issue

Notice the top and left sides of the screen. They should be black (the area is not currently there). Instead, whatever was drawn in the previous frame remains, leaving a graphical artifact.

<img width="592" alt="screen shot 2016-10-24 at 11 12 19 pm" src="https://cloud.githubusercontent.com/assets/107998/19674798/5ddc7a02-9a3f-11e6-9dfb-31e821051023.png">

**Comment by seisatsu** [comment]
Yeah, I noticed this, but overlooked it when the window was the size of each area because all four edges would have been black while rumbling. The effect of graphics cloning off the side of the screen could actually trick my eyes to think there was something over there to render. Anyway, I think we can just fix this and then make areas where rumbles happen big enough to handle it without showing letterbox.

**Comment by seisatsu** [comment]
I am having a hell of a time just trying to paint black on the screen between frames.

**Comment by seisatsu** [comment]
One last detail -- we need to be able to cover up tall entities spilling over the edge of the area before I can mark this fixed.

**Comment by pmer** [comment]
I am thinking of adding a clip to the src and dest rectangles on every overlay draw & clipping to the area boundaries. What do you think @seisatsu?

**Comment by seisatsu** [comment]
A clip is probably what's going to have to happen.
