### ISSUE TITLE
Initialize some window settings in Python

### ISSUE THREAD

**Issue by pmer** [seisatsu/Driftwood#97]
This also allows them to be modified during runtime.

**Comment by seisatsu** [comment]
Complication: The window is initialized before we load the init script.

**Comment by pmer** [comment]
Hmm, I may have come off a little strong. I just think the viewport dimensions should receive the same treatment that the rest of the game's content does.

Anyway, the viewport can easily be changed at runtime after the window is initialized. Same thing with the window title if we want.

**Comment by seisatsu** [comment]
True, the scripts can override any setting. Then, the real goal here is to allow the logical window size to be changed during runtime.

**Comment by pmer** [comment]
Should we remove them from the config file?

**Comment by seisatsu** [comment]
Nah, since they can be overridden in the code, there's not much point to removing them. Also, the config file only sets window width and height, from which logical width and height is calculated, iirc. If we can change logical width and height in the code, then there is utility in the user being able to set the size of the window and have it stretch.

**Comment by seisatsu** [comment]
I will close this once we confirm changing logical size during runtime works.

**Comment by seisatsu** [comment]
It works.
